-- Seed Digital Systems Readiness Assessment
INSERT INTO interactive.assessment_templates (slug, title, description, version, is_active)
VALUES ('digital-readiness', 'Digital Systems Readiness Assessment', 'A 15-question evaluation across 5 dimensions: Strategy, Data, Infrastructure, Security, and Operations.', 1, TRUE)
ON CONFLICT (slug) DO NOTHING;

DO $$
DECLARE
    tpl_id UUID;
BEGIN
    SELECT id INTO tpl_id FROM interactive.assessment_templates WHERE slug = 'digital-readiness';
    IF tpl_id IS NULL THEN RETURN; END IF;

    DELETE FROM interactive.assessment_questions WHERE template_id = tpl_id;

    INSERT INTO interactive.assessment_questions (template_id, question_text, dimension, question_order, options) VALUES
    (tpl_id, 'Does your organisation have a documented digital strategy aligned to business objectives?', 'strategy', 1, '[{"label":"No strategy exists","value":1,"weight":1.0},{"label":"Informal or outdated","value":2,"weight":1.0},{"label":"Documented but not fully implemented","value":3,"weight":1.0},{"label":"Active and reviewed annually","value":4,"weight":1.0},{"label":"Dynamic, data-driven strategy with quarterly reviews","value":5,"weight":1.0}]'),
    (tpl_id, 'How well do digital initiatives align with your organisation''s 3-year roadmap?', 'strategy', 2, '[{"label":"No alignment","value":1,"weight":1.0},{"label":"Limited awareness","value":2,"weight":1.0},{"label":"Partial alignment","value":3,"weight":1.0},{"label":"Well aligned","value":4,"weight":1.0},{"label":"Fully integrated into strategic planning","value":5,"weight":1.0}]'),
    (tpl_id, 'Is there executive sponsorship (C-level or equivalent) for digital transformation?', 'strategy', 3, '[{"label":"No sponsorship","value":1,"weight":1.0},{"label":"Mid-level interest only","value":2,"weight":1.0},{"label":"Single executive champion","value":3,"weight":1.0},{"label":"C-level steering committee","value":4,"weight":1.0},{"label":"Board-level digital mandate with budget ownership","value":5,"weight":1.0}]'),

    (tpl_id, 'How is your organisation''s data currently stored and managed?', 'data', 4, '[{"label":"Scattered spreadsheets and paper","value":1,"weight":1.0},{"label":"Basic databases, no integration","value":2,"weight":1.0},{"label":"Centralised database with some integrations","value":3,"weight":1.0},{"label":"Data warehouse or lake with governance","value":4,"weight":1.0},{"label":"Enterprise data platform with real-time analytics","value":5,"weight":1.0}]'),
    (tpl_id, 'Do you have established data quality standards and monitoring?', 'data', 5, '[{"label":"No standards","value":1,"weight":1.0},{"label":"Ad-hoc cleaning","value":2,"weight":1.0},{"label":"Defined standards, manual enforcement","value":3,"weight":1.0},{"label":"Automated quality checks and dashboards","value":4,"weight":1.0},{"label":"ML-powered anomaly detection and lineage tracking","value":5,"weight":1.0}]'),
    (tpl_id, 'Can your organisation generate actionable insights from data within 24 hours?', 'data', 6, '[{"label":"Not possible","value":1,"weight":1.0},{"label":"Takes weeks or months","value":2,"weight":1.0},{"label":"Basic reports within a week","value":3,"weight":1.0},{"label":"Standard dashboards updated daily","value":4,"weight":1.0},{"label":"Real-time streaming analytics and predictive models","value":5,"weight":1.0}]'),

    (tpl_id, 'What is the current state of your core IT infrastructure?', 'infrastructure', 7, '[{"label":"Legacy on-premise with no cloud","value":1,"weight":1.0},{"label":"Limited cloud adoption","value":2,"weight":1.0},{"label":"Hybrid cloud with basic orchestration","value":3,"weight":1.0},{"label":"Cloud-native with containerisation","value":4,"weight":1.0},{"label":"Multi-cloud with auto-scaling and edge deployment","value":5,"weight":1.0}]'),
    (tpl_id, 'How do you handle system downtime or failures?', 'infrastructure', 8, '[{"label":"Reactive, no plan","value":1,"weight":1.0},{"label":"Basic backup recovery","value":2,"weight":1.0},{"label":"Defined disaster recovery plan","value":3,"weight":1.0},{"label":"Automated failover and monitoring","value":4,"weight":1.0},{"label":"Chaos engineering and SLO-driven reliability","value":5,"weight":1.0}]'),
    (tpl_id, 'Are your systems API-first and interoperable with external platforms?', 'infrastructure', 9, '[{"label":"No APIs","value":1,"weight":1.0},{"label":"Limited APIs, undocumented","value":2,"weight":1.0},{"label":"Documented APIs for core functions","value":3,"weight":1.0},{"label":"API gateway with developer portal","value":4,"weight":1.0},{"label":"Event-driven architecture with open standards","value":5,"weight":1.0}]'),

    (tpl_id, 'Does your organisation have a formal information security policy?', 'security', 10, '[{"label":"No policy","value":1,"weight":1.0},{"label":"Informal guidelines","value":2,"weight":1.0},{"label":"Documented policy, partial compliance","value":3,"weight":1.0},{"label":"Certified (ISO 27001, SOC 2, or equivalent)","value":4,"weight":1.0},{"label":"Continuous security monitoring and red-teaming","value":5,"weight":1.0}]'),
    (tpl_id, 'How do you manage user access and identity?', 'security', 11, '[{"label":"Shared credentials","value":1,"weight":1.0},{"label":"Basic username/password","value":2,"weight":1.0},{"label":"Role-based access control (RBAC)","value":3,"weight":1.0},{"label":"SSO + MFA with privileged access management","value":4,"weight":1.0},{"label":"Zero-trust architecture with continuous verification","value":5,"weight":1.0}]'),
    (tpl_id, 'Have you conducted a penetration test or security audit in the last 12 months?', 'security', 12, '[{"label":"Never","value":1,"weight":1.0},{"label":"Over 2 years ago","value":2,"weight":1.0},{"label":"Over 1 year ago","value":3,"weight":1.0},{"label":"Within last 12 months","value":4,"weight":1.0},{"label":"Quarterly automated + annual external audit","value":5,"weight":1.0}]'),

    (tpl_id, 'How are business processes documented and optimised?', 'operations', 13, '[{"label":"Not documented","value":1,"weight":1.0},{"label":"Ad-hoc documentation","value":2,"weight":1.0},{"label":"Standard operating procedures exist","value":3,"weight":1.0},{"label":"Process mining and continuous improvement","value":4,"weight":1.0},{"label":"AI-assisted workflow optimisation and automation","value":5,"weight":1.0}]'),
    (tpl_id, 'What is your approach to software development and deployment?', 'operations', 14, '[{"label":"Ad-hoc/manual deployments","value":1,"weight":1.0},{"label":"Basic version control","value":2,"weight":1.0},{"label":"CI/CD pipeline with testing","value":3,"weight":1.0},{"label":"DevOps with automated testing and deployment","value":4,"weight":1.0},{"label":"Platform engineering with GitOps and feature flags","value":5,"weight":1.0}]'),
    (tpl_id, 'How do you measure and improve digital service delivery to citizens or customers?', 'operations', 15, '[{"label":"No measurement","value":1,"weight":1.0},{"label":"Basic satisfaction surveys","value":2,"weight":1.0},{"label":"KPIs tracked monthly","value":3,"weight":1.0},{"label":"Real-time feedback loops and NPS tracking","value":4,"weight":1.0},{"label":"Predictive service design with personalisation","value":5,"weight":1.0}]');
END $$;
