-- Seed data for Layer 06: Annotated Bibliography, Audio Briefs, Webinars

-- Reading List Items (Annotated Bibliography)
INSERT INTO content.reading_list_items (slug, title, author, source_publication, source_url, published_year, annotation, key_takeaway, category, tags, read_time_minutes, recommended, status)
VALUES
('digital-transformation-africa', 'Digital Transformation in Africa: A Government Perspective', 'Dr. Amina Diallo', 'Journal of African Digital Policy', 'https://example.com/digital-transformation-africa', 2024, 'A comprehensive survey of digital transformation initiatives across twelve African governments. Diallo identifies three failure modes that recur in 73% of abandoned projects: premature platform selection before process mapping, insufficient change management capacity, and politically driven timelines that ignore technical reality. The paper''s framework for assessing government readiness is directly applicable to the work XCreativs does with the 24-Hour Economy Authority.', 'Government digital transformation fails most often at the intersection of political urgency and technical patience.', 'governance', '["digital transformation", "government", "Africa", "policy"]', 25, true, 'published'),

('platform-economics-healthcare', 'Platform Economics in Healthcare: The Ghanaian Case', 'Prof. Kwame Asante', 'Health Systems Innovation Review', 'https://example.com/platform-economics-healthcare', 2025, 'Asante builds a detailed economic model for health intelligence platforms in resource-constrained settings. The key insight is that platform economics in Ghana differ fundamentally from Western models because the payer mix is fragmented (NHIS, private insurance, out-of-pocket, donor-funded) and data liquidity is low. The paper argues for a phased monetisation strategy that begins with operational efficiency gains before attempting data-driven revenue models.', 'Health platforms in Ghana must prioritise operational efficiency over data monetisation in their first three years.', 'strategy', '["healthcare", "platform economics", "Ghana", "ILIVVON"]', 30, true, 'published'),

('ai-readiness-enterprise', 'Enterprise AI Readiness: A Framework for Sub-Saharan Africa', 'Dr. Sarah Okafor', 'MIT Technology Review Africa', 'https://example.com/ai-readiness-enterprise', 2024, 'Okafor''s framework identifies five maturity levels for enterprise AI adoption, from "data-aware" to "AI-native." Critically, she notes that most African enterprises are stuck at level two ("data-collecting") not because of technology gaps but because of organisational silos that prevent data from flowing across departments. The paper includes a diagnostic tool that maps closely to XCreativs'' engagement readiness diagnostic.', 'AI readiness is 80% organisational and 20% technical in the African enterprise context.', 'technology', '["AI", "enterprise", "framework", "readiness"]', 20, false, 'published'),

('designing-for-scale', 'Designing Digital Systems for National Scale', 'James Chen', 'Stanford Digital Society Review', 'https://example.com/designing-for-scale', 2023, 'Chen examines three national-scale digital systems that succeeded (Estonia e-Residency, India Stack, Singapore SingPass) and three that failed (Kenya Huduma Namba, Nigeria NIMC early phase, South Africa e-HomeAffairs). The pattern that separates success from failure is architectural: successful systems are built as platforms with clear API boundaries from day one; failed systems are built as monolithic applications that later attempt to become platforms.', 'National-scale systems must be architected as platforms from day one, not refactored into platforms later.', 'design', '["national scale", "architecture", "platforms", "API"]', 35, true, 'published'),

('public-private-partnerships', 'Public-Private Partnerships in Digital Infrastructure', 'Dr. Fatima Al-Hassan', 'World Bank Digital Development Reports', 'https://example.com/public-private-partnerships', 2024, 'Al-Hassan reviews the contractual and governance structures of twenty public-private digital infrastructure partnerships across Africa. The most successful partnerships share three characteristics: clear IP ownership clauses that incentivise ongoing innovation, revenue-sharing models that align long-term interests, and governance structures that include technical stakeholders in decision-making rather than treating technology as a procurement category.', 'Successful digital PPPs treat technology as a strategic partnership, not a procurement category.', 'operations', '["PPP", "digital infrastructure", "governance", "IP"]', 28, false, 'published');

-- Audio Briefs
INSERT INTO content.audio_briefs (slug, title, summary, duration_seconds, audio_url, transcript, speaker_name, speaker_title, tags, published_at, status)
VALUES
('brief-national-id-2025', 'Why National ID Systems Fail — And How to Build One That Doesn''t', 'A twelve-minute analysis of the architectural and governance decisions that separate successful national identity systems from expensive failures. Draws on XCreativs'' experience advising three African governments on identity infrastructure.', 720, 'https://cdn.xcreativs.com/audio/brief-national-id-2025.mp3', 'National identity systems are not technology projects. They are trust architecture projects. The technology is the easy part. The hard part is designing a system that every citizen trusts enough to enrol in, every government agency trusts enough to depend on, and every subsequent digital service can integrate with without rebuilding. In this brief, we examine the three architectural patterns that have succeeded at national scale...', 'Shayford K. K. Sarfo', 'Founder, XCreativs Technologies', '["national ID", "identity", "architecture", "government"]', '2025-11-15T09:00:00Z', 'published'),

('brief-health-intelligence', 'Health Intelligence Platforms: The Business Model Nobody Talks About', 'An eight-minute brief on why health intelligence platforms in Africa must be designed for operational efficiency first, and data monetisation second. Based on XCreativs'' work on the ILIVVON platform.', 480, 'https://cdn.xcreativs.com/audio/brief-health-intelligence.mp3', 'Everyone talks about the data. Health intelligence platforms generate extraordinary amounts of clinical, operational, and financial data. But in the African context, the business model that works is not selling that data. It is using that data to make the health system operate more efficiently. In this brief, we explain why ILIVVON''s revenue model is built on operational savings, not data sales...', 'Shayford K. K. Sarfo', 'Founder, XCreativs Technologies', '["health", "ILIVVON", "business model", "platform"]', '2025-12-01T09:00:00Z', 'published'),

('brief-24h-economy', 'The 24-Hour Economy: What It Actually Means for Digital Infrastructure', 'A ten-minute brief on the digital infrastructure implications of Ghana''s 24-Hour Economy policy. Covers the three technology layers that must be in place before a 24-hour economy can function.', 600, 'https://cdn.xcreativs.com/audio/brief-24h-economy.mp3', 'The 24-Hour Economy is not about keeping shops open later. It is about building digital infrastructure that enables economic activity to flow continuously across time zones, regulatory boundaries, and payment systems. In this brief, we break down the three layers that must be in place: the identity layer, the payment layer, and the regulatory layer...', 'Shayford K. K. Sarfo', 'Founder, XCreativs Technologies', '["24-hour economy", "Ghana", "digital infrastructure", "policy"]', '2025-12-20T09:00:00Z', 'published');

-- Webinars
INSERT INTO content.webinars (slug, title, description, scheduled_at, duration_minutes, speaker_names, tags, status)
VALUES
('webinar-platform-economics-2026', 'Platform Economics for African Enterprises', 'A deep-dive webinar on how African enterprises can design platform business models that account for fragmented markets, low data liquidity, and mixed payer ecosystems. We will examine three case studies: a health platform, a logistics platform, and a government services platform.', '2026-06-15T14:00:00Z', 90, '["Shayford K. K. Sarfo", "Dr. Kwame Asante"]', '["platform economics", "business model", "Africa"]', 'upcoming'),

('webinar-gov-digital-readiness', 'Assessing Government Digital Readiness: A Practical Framework', 'Governments across Africa are launching ambitious digital transformation programmes. Most will fail. This webinar presents a practical framework for assessing readiness before committing capital, based on XCreativs'' experience with the 24-Hour Economy Authority and similar mandates.', '2026-07-10T13:00:00Z', 75, '["Shayford K. K. Sarfo"]', '["government", "digital readiness", "assessment", "framework"]', 'upcoming'),

('webinar-ai-automation-2026', 'AI and Automation for African Enterprises: Beyond the Hype', 'A technical and strategic webinar on what AI and automation can actually deliver for African enterprises today. We cover four proven use cases, three common pitfalls, and a roadmap for building internal AI capability without outsourcing your strategic advantage.', '2026-05-20T14:00:00Z', 60, '["Shayford K. K. Sarfo", "Dr. Sarah Okafor"]', '["AI", "automation", "enterprise", "strategy"]', 'recorded');
