-- Seed data for Phase A development

-- Services
INSERT INTO content.services (slug, service_line, title, title_fr, summary, summary_fr, methodology, deliverables, indicative_timeline, indicative_price_band, faqs, sort_order, status) VALUES
('digital_systems_audit', 'digital_systems_audit', 'Digital Systems Audit & Architecture', 'Audit et Architecture des Systèmes Numériques', 'A structured engagement that audits a client''s digital posture and produces an architecture for the next eighteen-to-thirty-six months.', 'Un engagement structuré qui audite la posture numérique d''un client et produit une architecture pour les dix-huit à trente-six prochains mois.', '["Discovery", "Assessment", "Architecture", "Roadmap"]', '["Audit report", "Architecture blueprint", "18-36 month roadmap", "Risk register"]', '4–8 weeks', '$15,000–$45,000', '[{"q":"What is included?","a":"Full discovery, assessment, architecture blueprint, and 18-36 month roadmap."}]', 1, 'published'),
('enterprise_government_systems', 'enterprise_government_systems', 'Enterprise & Government System Development', 'Développement de Systèmes d''Entreprise et Gouvernementaux', 'Mission-critical builds for institutions. Selective, not open.', 'Des constructions critiques pour les institutions. Sélectif, pas ouvert.', '["Governance", "Design", "Build", "Deploy", "Support"]', '["Production system", "Documentation", "Training", "SLA"]', '12–36 weeks', '$75,000–$500,000', '[{"q":"Do you work with all governments?","a":"We are selective and evaluate fit before engagement."}]', 2, 'published'),
('ai_automation', 'ai_automation', 'AI & Automation Integration', 'Intégration de l''IA et de l''Automatisation', 'The intelligence layer: document intelligence, workflow automation, predictive layers, copilots.', 'La couche intelligence: intelligence documentaire, automatisation des flux, couches prédictives, copilotes.', '["Feasibility", "Data audit", "Model selection", "Integration", "Evaluation"]', '["AI module", "Integration layer", "Evaluation framework", "Runbook"]', '8–24 weeks', '$50,000–$300,000', '[{"q":"Is my data safe?","a":"We operate sovereign-by-default and can deploy on-premise or in-region."}]', 3, 'published'),
('strategic_web_platforms', 'strategic_web_platforms', 'Strategic Web & Digital Platforms', 'Plateformes Web et Numériques Stratégiques', 'Web platforms taken where they earn strategic position, not as agency work.', 'Des plateformes web prises là où elles gagnent une position stratégique, pas comme du travail d''agence.', '["Strategy", "Design", "Build", "Launch", "Iterate"]', '["Platform", "Design system", "Analytics", "Growth plan"]', '6–16 weeks', '$30,000–$150,000', '[{"q":"Do you build brochure sites?","a":"No. We build platforms that become infrastructure."}]', 4, 'published'),
('strategy_advisory', 'strategy_advisory', 'Strategy, Advisory & Thought Leadership', 'Stratégie, Conseil et Leadership d''Opinion', 'The authority engine: retainer model, advisory boards, publication track record.', 'Le moteur d''autorité: modèle de rétainer, conseils d''administration, bilan de publication.', '["Diagnostic", "Advisory retainer", "Board participation", "Publication"]', '["Strategy memo", "Advisory sessions", "Board pack", "Published thesis"]', 'Ongoing', '$5,000–$20,000/month', '[{"q":"What is the commitment?","a":"Minimum 6-month retainer with quarterly review."}]', 5, 'published');

-- Labs Products
INSERT INTO content.labs_products (slug, name, name_fr, tagline, tagline_fr, problem_statement, problem_statement_fr, platform_description, platform_description_fr, technical_architecture_overview, sectors, sort_order, status) VALUES
('ilivvon', 'ILIVVON', 'ILIVVON', 'Health Intelligence Platform', 'Plateforme d''Intelligence Sanitaire', 'Healthcare in Africa suffers from fragmented data, poor referral chains, and reactive rather than predictive care.', 'La santé en Afrique souffre de données fragmentées, de chaînes de référence médiocres et de soins réactifs plutôt que prédictifs.', 'ILIVVON unifies patient records, referral networks, and predictive health analytics into a single sovereign platform.', 'ILIVVON unifie les dossiers patients, les réseaux de référence et les analyses sanitaires prédictives en une seule plateforme souveraine.', 'Microservices architecture with event sourcing, PostgreSQL for transactional data, ClickHouse for analytics, and on-premise deployment option.', '["health", "government", "ngo_development"]', 1, 'published');

-- Subsidiaries
INSERT INTO content.subsidiaries (slug, name, name_fr, description, description_fr, status, leadership, relationship_to_parent, sort_order) VALUES
('ilivvon-health-systems', 'ILIVVON Health Systems Ltd', 'ILIVVON Health Systems Ltd', 'Spun out from Labs to own and operate the ILIVVON platform across West Africa.', 'Spin-off de Labs pour posséder et exploiter la plateforme ILIVVON en Afrique de l''Ouest.', 'in_formation', '[{"name":"Dr. Ama Mensah","role":"CEO"}]', ' wholly-owned subsidiary of XCreativs Technologies', 1);

-- Case Dossiers
INSERT INTO content.case_dossiers (slug, title, title_fr, client_name, industry, service_line, scale, stage, brief, brief_fr, what_shipped, what_shipped_fr, anonymized, sort_order, status) VALUES
('24h-economy-authority', '24H+ Authority Intelligence Architecture', 'Architecture d''Intelligence 24H+', '24-Hour Economy Authority of Ghana', 'government', 'enterprise_government_systems', 'national', 'active', 'Design and build a national intelligence platform for the 24-Hour Economy Authority to coordinate policy, investment, and enforcement across Ghana.', 'Concevoir et construire une plateforme d''intelligence nationale pour l''Autorité de l''Économie 24H afin de coordonner la politique, l''investissement et l''application au Ghana.', 'A live intelligence architecture with donor intelligence engine, regulatory coordination layer, and investor portal.', 'Une architecture d''intelligence en direct avec moteur d''intelligence des donateurs, couche de coordination réglementaire et portail investisseur.', false, 1, 'published'),
('fastcare-clinics', 'ILIVVON for Fastcare Clinics', 'ILIVVON pour Fastcare Clinics', 'Fastcare Clinics', 'health', 'ai_automation', 'enterprise', 'active', 'Deploy the ILIVVON health intelligence platform across Fastcare clinic network to unify patient data and enable predictive care.', 'Déployer la plateforme d''intelligence sanitaire ILIVVON dans le réseau de cliniques Fastcare pour unifier les données patients et permettre des soins prédictifs.', 'Live platform across 12 clinics with unified EMR, referral network, and AI-powered triage.', 'Plateforme en direct dans 12 cliniques avec EMR unifié, réseau de référence et triage alimenté par l''IA.', false, 2, 'published'),
('national-insurance-platform', 'National Insurance Digitisation', 'Numérisation des Assurances Nationales', 'National Insurance Commission', 'financial_services', 'enterprise_government_systems', 'national', 'completed', 'Modernise the national insurance registry, claims processing, and regulatory reporting.', 'Moderniser le registre national des assurances, le traitement des réclamations et les rapports réglementaires.', 'A unified digital registry with real-time claims processing and regulatory dashboard.', 'Un registre numérique unifié avec traitement des réclamations en temps réel et tableau de bord réglementaire.', true, 3, 'published'),
('retail-commerce-hub', 'West African Retail Commerce Hub', 'Hub de Commerce de Détail Ouest-Africain', 'Major Retail Consortium', 'retail_commerce', 'strategic_web_platforms', 'regional', 'completed', 'Build a unified B2B commerce platform connecting suppliers, distributors, and retailers across Ghana, Nigeria, and Cote d''Ivoire.', 'Construire une plateforme de commerce B2B unifiée connectant fournisseurs, distributeurs et détaillants au Ghana, au Nigeria et en Côte d''Ivoire.', 'Live platform processing 50,000+ orders monthly with integrated logistics and payments.', 'Plateforme en direct traitant plus de 50 000 commandes mensuelles avec logistique et paiements intégrés.', true, 4, 'published'),
('energy-grid-monitoring', 'Grid Intelligence for Energy Utility', 'Intelligence de Réseau pour Service Public d''Énergie', 'National Energy Utility', 'energy', 'digital_systems_audit', 'national', 'completed', 'Audit and architect a real-time monitoring layer for the national electricity grid.', 'Auditer et architecturer une couche de surveillance en temps réel pour le réseau électrique national.', 'Real-time SCADA integration with predictive maintenance and outage management.', 'Intégration SCADA en temps réel avec maintenance prédictive et gestion des pannes.', true, 5, 'published');

-- Industries
INSERT INTO content.industries (slug, sector, title, title_fr, description, description_fr, capability_mapping, relevant_dossier_slugs, intake_cta_text, intake_cta_text_fr, sort_order, status) VALUES
('government', 'government', 'Government', 'Gouvernement', 'National-scale digital systems for policy, regulation, and public service delivery.', 'Des systèmes numériques à l''échelle nationale pour la politique, la réglementation et la prestation de services publics.', '[{"capability":"Enterprise Systems","description":"Mission-critical platforms for government operations."}]', '["24h-economy-authority"]', 'Discuss a government mandate', 'Discuter d''un mandat gouvernemental', 1, 'published'),
('health', 'health', 'Health', 'Santé', 'Intelligent health platforms, from clinics to national health information systems.', 'Plateformes sanitaires intelligentes, des cliniques aux systèmes d''information sanitaire nationale.', '[{"capability":"AI Integration","description":"Predictive analytics and intelligent triage."}]', '["fastcare-clinics"]', 'Explore health intelligence', 'Explorer l''intelligence sanitaire', 2, 'published'),
('financial-services', 'financial_services', 'Financial Services', 'Services Financiers', 'Digital infrastructure for banks, insurers, and regulators.', 'Infrastructure numérique pour banques, assureurs et régulateurs.', '[{"capability":"Audit & Architecture","description":"Regulatory-compliant system design."}]', '["national-insurance-platform"]', 'Assess your financial systems', 'Évaluer vos systèmes financiers', 3, 'published'),
('insurance', 'insurance', 'Insurance', 'Assurance', 'Claims, underwriting, and distribution platforms.', 'Plateformes de réclamations, souscription et distribution.', '[{"capability":"Enterprise Systems","description":"End-to-end insurance digitisation."}]', '["national-insurance-platform"]', 'Digitise insurance operations', 'Numériser les opérations d''assurance', 4, 'published'),
('retail-commerce', 'retail_commerce', 'Retail & Commerce', 'Commerce de Détail', 'B2B and B2C platforms for modern African commerce.', 'Plateformes B2B et B2C pour le commerce africain moderne.', '[{"capability":"Web Platforms","description":"Scalable commerce infrastructure."}]', '["retail-commerce-hub"]', 'Build your commerce platform', 'Construire votre plateforme de commerce', 5, 'published'),
('energy', 'energy', 'Energy', 'Énergie', 'Grid monitoring, predictive maintenance, and utility management.', 'Surveillance de réseau, maintenance prédictive et gestion des services publics.', '[{"capability":"AI Integration","description":"Predictive maintenance and outage intelligence."}]', '["energy-grid-monitoring"]', 'Modernise energy infrastructure', 'Moderniser l''infrastructure énergétique', 6, 'published'),
('education', 'education', 'Education', 'Éducation', 'Learning management, student information systems, and credential verification.', 'Gestion de l''apprentissage, systèmes d''information étudiants et vérification des credentials.', '[{"capability":"Audit & Architecture","description":"Digital transformation roadmaps for institutions."}]', '[]', 'Transform education delivery', 'Transformer la prestation de l''éducation', 7, 'published'),
('ngo-development', 'ngo_development', 'NGO & Development', 'ONG & Développement', 'Systems for multilaterals, NGOs, and development finance.', 'Systèmes pour les multilatérales, ONG et financement du développement.', '[{"capability":"Strategy & Advisory","description":"Thought leadership and system design for development outcomes."}]', '[]', 'Partner on development systems', 'Collaborer sur les systèmes de développement', 8, 'published');

-- Insights
INSERT INTO content.insights (slug, content_type, title, title_fr, summary, summary_fr, body, body_fr, author_name, author_title, tags, is_gated, published_at, status) VALUES
('field-note-1', 'field_note', 'The cost of reactive government IT', 'Le coût des TI gouvernementales réactives', 'Most government IT spend is on maintenance of systems that were outdated before they launched. The alternative is architecture-first procurement.', 'La majeure partie des dépenses IT gouvernementales concerne la maintenance de systèmes obsolètes avant même leur lancement. L''alternative est un achat axé sur l''architecture.', 'Full body here...', 'Corps complet ici...', 'Shay Ford', 'Founder', '["government","procurement","architecture"]', false, NOW(), 'published'),
('thesis-1', 'thesis', 'The Architecture of Intelligent Government in West Africa', 'L''Architecture d''un Gouvernement Intelligent en Afrique de l''Ouest', 'A 15,000-word thesis on how West African governments can build intelligent digital systems that compound rather than decay.', 'Une thèse de 15 000 mots sur la façon dont les gouvernements ouest-africains peuvent construire des systèmes numériques intelligents qui se renforcent plutôt que se dégradent.', 'Full thesis body...', 'Corps complet de la thèse...', 'Shay Ford', 'Founder', '["government","ai","strategy"]', true, NOW(), 'published');

-- Glossary
INSERT INTO content.glossary (term, term_fr, definition, definition_fr, related_terms, sort_order) VALUES
('Leverage Points', 'Points de Levier', 'Places within a complex system where a small shift can lead to large changes in the entire system. From Donella Meadows.', 'Des endroits dans un système complexe où un petit changement peut entraîner de grands changements dans tout le système. De Donella Meadows.', '["Systems Thinking","Intervention"]', 1),
('Capability Lattice', 'Réseau de Capacités', 'The intersecting grid of all firm capabilities against all sectors served.', 'La grille d''intersection de toutes les capacités de l''entreprise avec tous les secteurs desservis.', '["Services","Sectors"]', 2),
('Sovereign-by-Default', 'Souverain par Défaut', 'The principle that client data belongs to the client, and systems should be architected for data sovereignty from day one.', 'Le principe selon lequel les données du client appartiennent au client, et les systèmes doivent être architecturés pour la souveraineté des données dès le premier jour.', '["Security","Privacy"]', 3),
('Embedded vs Engaged', 'Intégré vs Engagé', 'Embedded: the firm operates as part of the client organization. Engaged: the firm delivers a scoped mandate and withdraws.', 'Intégré: l''entreprise opère comme partie de l''organisation client. Engagé: l''entreprise livre un mandat cadré et se retire.', '["Engagement Model"]', 4),
('Intelligent Digital Systems', 'Systèmes Numériques Intelligents', 'Digital platforms that incorporate AI, predictive analytics, and automation to operate with reduced human intervention.', 'Plateformes numériques qui intègrent l''IA, l''analyse prédictive et l''automatisation pour fonctionner avec une intervention humaine réduite.', '["AI","Automation"]', 5);

-- FAQs
INSERT INTO content.faqs (category, category_fr, question, question_fr, answer, answer_fr, sort_order) VALUES
('Engagement Model', 'Modèle d''Engagement', 'How do you price engagements?', 'Comment fixez-vous les prix des engagements?', 'We work on milestone-based pricing with clear deliverables and payment schedules. Large government mandates may include a retainer component.', 'Nous travaillons sur des prix basés sur des jalons avec des livrables et des calendriers de paiement clairs. Les grands mandats gouvernementaux peuvent inclure une composante de rétainer.', 1),
('Security & Compliance', 'Sécurité et Conformité', 'Where is data stored?', 'Où les données sont-elles stockées?', 'By default, data is stored in-region. We offer on-premise deployment for sovereignty-conscious clients.', 'Par défaut, les données sont stockées dans la région. Nous offrons un déploiement sur site pour les clients soucieux de souveraineté.', 2),
('IP', 'PI', 'Who owns the intellectual property?', 'Qui détient la propriété intellectuelle?', 'Client-specific customizations belong to the client. Platform IP we build during engagements is retained by XCreativs Labs and licensed back.', 'Les personnalisations spécifiques au client appartiennent au client. Les IP de plateforme que nous construisons pendant les engagements sont conservées par XCreativs Labs et concédées sous licence.', 3);

-- Press
INSERT INTO content.press_releases (slug, title, title_fr, body, body_fr, published_at, is_coverage, source_name, status) VALUES
('launch-announcement', 'XCreativs Technologies Announces New Web Platform', 'XCreativs Technologies Annonce une Nouvelle Plateforme Web', 'XCreativs Technologies today announced the launch of its new web platform...', 'XCreativs Technologies annonce aujourd''hui le lancement de sa nouvelle plateforme web...', NOW(), false, NULL, 'published');

-- Media Kit
INSERT INTO content.media_kit (asset_type, name, download_url, sort_order) VALUES
('logo', 'XCreativs Primary Logo', 'https://assets.xcreativs.com/logo-primary.png', 1),
('logo', 'XCreativs Monochrome Logo', 'https://assets.xcreativs.com/logo-mono.png', 2),
('one_pager', 'Company One-Pager', 'https://assets.xcreativs.com/one-pager.pdf', 3);

-- Pages
INSERT INTO content.pages (slug, title, title_fr, data, status) VALUES
('home', 'Home', 'Accueil', '{"hero":"Intelligent digital systems for governments and enterprises.","manifesto":"We build infrastructure that compounds."}', 'published'),
('about', 'About', 'À Propos', '{"mission":"To build intelligent digital systems that governments and enterprises cannot operate without.","founders":[{"name":"Shay Ford","title":"Founder & CEO"}]}', 'published');

-- Diagnostic Questions
INSERT INTO lead_qual.diagnostic_questions (question_key, question_text, question_text_fr, question_type, options, sort_order, is_active) VALUES
('who_are_you', 'Who are you?', 'Qui êtes-vous?', 'single_choice', '[{"value":"government","label":"Government body"},{"value":"enterprise","label":"Enterprise"},{"value":"ngo","label":"NGO / Multilateral"},{"value":"startup","label":"Startup"}]', 1, true),
('brief_summary', 'In one sentence, what is the brief?', 'En une phrase, quel est le mandat?', 'text', '[]', 2, true),
('mission_criticality', 'How mission-critical is this?', 'À quel point est-ce critique?', 'single_choice', '[{"value":"essential","label":"Essential to operations"},{"value":"important","label":"Important but not blocking"},{"value":"exploratory","label":"Exploratory"}]', 3, true),
('budget_signal', 'What is your indicative budget range?', 'Quelle est votre fourchette budgétaire indicative?', 'single_choice', '[{"value":"under_50k","label":"Under $50,000"},{"value":"50k_150k","label":"$50,000 – $150,000"},{"value":"150k_500k","label":"$150,000 – $500,000"},{"value":"over_500k","label":"Over $500,000"}]', 4, true),
('timeline', 'What is your target timeline?', 'Quel est votre calendrier cible?', 'single_choice', '[{"value":"urgent","label":"Under 3 months"},{"value":"standard","label":"3–6 months"},{"value":"flexible","label":"6–12 months"},{"value":"strategic","label":"12+ months"}]', 5, true);

-- Talent: Job Roles
INSERT INTO talent.job_roles (
    slug, title, title_fr, department, location, is_remote_friendly, employment_type,
    summary, summary_fr, responsibilities, requirements, compensation_philosophy,
    growth_trajectory, project_examples, team_description, application_process,
    expected_start_window, is_open, published_at
) VALUES
('senior-systems-architect', 'Senior Systems Architect', 'Architecte Systèmes Senior', 'Enterprise Systems', 'Accra / Remote', true, 'full_time', 'Lead architecture reviews and shape high-dependability digital platforms for institutional clients.', 'Diriger les revues d''architecture et concevoir des plateformes numériques fiables pour les institutions.', '["Lead architecture reviews for client programmes","Translate institutional requirements into secure system designs","Set delivery standards for backend, data, and integration work","Coach engineers through critical implementation decisions"]', '["8+ years building production systems","Strong systems architecture and database design judgement","Experience with regulated or mission-critical environments","Clear written and executive communication"]', 'Above-market base for Ghana with project success incentives and Labs upside for exceptional contributors.', 'Path to Principal Architect or Delivery CTO for major institutional programmes.', '["National-scale portal modernization","Digital systems audit for a regulated enterprise","Secure workflow platform for multi-stakeholder operations"]', 'Small senior delivery team with engineering, product, advisory, and client strategy leads.', 'Application review, architecture discussion, practical systems exercise, and final leadership conversation.', 'Q3 2026', true, NOW()),
('senior-backend-engineer', 'Senior Backend Engineer', 'Ingénieur Backend Senior', 'Engineering', 'Accra / Remote', true, 'full_time', 'Build national-scale systems in Go and PostgreSQL. Work on the client portal, APIs, and infrastructure.', 'Construire des systèmes à l''échelle nationale en Go et PostgreSQL. Travailler sur le portail client, les API et l''infrastructure.', '["Design and implement high-performance APIs","Optimize PostgreSQL queries and schema","Own integrations with partner and client systems","Mentor mid-level engineers through production delivery"]', '["5+ years backend engineering experience","Strong Go or comparable systems-language experience","Deep SQL and data-modeling skill","Comfort owning features from design to observability"]', 'Above-market for Ghana with project bonuses and Labs spin-out participation for exceptional contributors.', 'Path to Staff Engineer or Engineering Lead within 24 months.', '["Client portal workflow engine","Billing, notification, and reporting APIs","Audit-ready data pipelines for institutional clients"]', 'Backend team embedded with product, design, and advisory leads on high-stakes client systems.', 'Application review, technical interview, code/design exercise, and final team conversation.', 'Immediate to Q3 2026', true, NOW()),
('product-designer', 'Product Designer', 'Designer Produit', 'Design', 'Accra / Remote', true, 'full_time', 'Design interfaces for platforms that governments, enterprises, and partner teams use every day.', 'Concevoir les interfaces de plateformes utilisées chaque jour par les gouvernements, entreprises et partenaires.', '["Own design system evolution across marketing and portal surfaces","Prototype complex workflows before engineering build","Conduct research with operators, executives, and field users","Partner with engineers until shipped UI feels polished"]', '["4+ years product design experience","Strong Figma and interaction prototyping practice","Design systems experience","Portfolio showing shipped operational or B2B products"]', 'Competitive base plus project bonuses for high-impact launches.', 'Path to Lead Designer or Design Director as the product system matures.', '["Admin portal IA and navigation redesign","Role-based dashboard workflow","Applicant and partner intake surfaces"]', 'Design works directly with engineering and client strategy rather than as a separate handoff layer.', 'Portfolio review, product critique, working session, and final team conversation.', 'Q3 2026', true, NOW()),
('ai-ml-engineer', 'AI / ML Engineer', 'Ingénieur IA / ML', 'Labs', 'Accra / Remote', true, 'full_time', 'Build document intelligence, predictive analytics, and copilots for national-scale platforms.', 'Construire l''intelligence documentaire, l''analyse prédictive et les copilotes pour des plateformes à l''échelle nationale.', '["Design reliable ML and retrieval pipelines","Deploy models and evaluation loops in production","Turn ambiguous client data into measurable product capabilities","Collaborate with domain experts and platform engineers"]', '["3+ years ML engineering experience","Python plus PyTorch, TensorFlow, or modern LLM tooling","MLOps or production evaluation experience","Strong product judgement around AI safety and reliability"]', 'Above-market base plus Labs equity participation for durable product contributions.', 'Path to Principal Scientist, Applied AI Lead, or Labs CTO.', '["Document intelligence for RFP review","Knowledge retrieval for client workspaces","Operational forecasting for delivery teams"]', 'Labs team builds reusable product capability from patterns discovered in client work.', 'Application review, ML systems conversation, practical evaluation exercise, and final Labs discussion.', 'Q3 to Q4 2026', true, NOW()),
('implementation-project-manager', 'Implementation Project Manager', 'Chef de Projet Implémentation', 'Delivery', 'Accra / Hybrid', true, 'contract', 'Coordinate client delivery across advisory, design, and engineering so institutional systems land cleanly.', 'Coordonner la livraison client entre conseil, design et ingénierie pour réussir les systèmes institutionnels.', '["Run delivery rituals across client and internal teams","Track risks, decisions, dependencies, and executive updates","Protect scope while keeping momentum","Translate ambiguity into crisp next actions"]', '["5+ years project or programme management experience","Experience with software delivery or digital transformation","Excellent written updates and stakeholder management","Calm operating style under pressure"]', 'Contract retainer with milestone bonuses for delivery outcomes.', 'Path to Programme Lead on larger public-sector or enterprise portfolios.', '["Government workflow modernization","Enterprise data platform rollout","Partner onboarding programme"]', 'Delivery sits close to the founder, engineering leads, and client executives.', 'Application review, delivery scenario discussion, writing sample, and final leadership conversation.', 'Q3 2026', true, NOW())
ON CONFLICT (slug) DO UPDATE SET
    title = EXCLUDED.title,
    title_fr = EXCLUDED.title_fr,
    department = EXCLUDED.department,
    location = EXCLUDED.location,
    is_remote_friendly = EXCLUDED.is_remote_friendly,
    employment_type = EXCLUDED.employment_type,
    summary = EXCLUDED.summary,
    summary_fr = EXCLUDED.summary_fr,
    responsibilities = EXCLUDED.responsibilities,
    requirements = EXCLUDED.requirements,
    compensation_philosophy = EXCLUDED.compensation_philosophy,
    growth_trajectory = EXCLUDED.growth_trajectory,
    project_examples = EXCLUDED.project_examples,
    team_description = EXCLUDED.team_description,
    application_process = EXCLUDED.application_process,
    expected_start_window = EXCLUDED.expected_start_window,
    is_open = EXCLUDED.is_open,
    published_at = COALESCE(talent.job_roles.published_at, EXCLUDED.published_at),
    updated_at = NOW();

-- Talent: Internship Programs
INSERT INTO talent.internship_programs (slug, title, title_fr, program_type, duration_months, description, description_fr, learning_outcomes, is_open, application_deadline) VALUES
('engineering-internship-2026', 'Engineering Internship Programme 2026', 'Programme de Stage en Ingénierie 2026', 'internship', 3, 'A structured three-month internship for software engineering students in Ghana and West Africa.', 'Un stage structuré de trois mois pour les étudiants en génie logiciel au Ghana et en Afrique de l''Ouest.', '["Build production features in Go","Work with raw PostgreSQL at scale","Learn clean architecture","Ship code to real users"]', true, '2026-08-01');
